TextToSpeech/TextToSpeech/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('', include('main.urls'))
]

TextToSpeech/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('temp', views.temp, name='temp'),
    path('translate', views.translate_view, name='translate'),
    path('text_utils', views.text_utils, name='text_utils'),
    path('text_to_speech', views.text_to_speech, name='text_to_speech'),
]

TextToSpeech/main/models.py
from django.db import models

# Create your models here.

TextToSpeech/main/forms.py
from django import forms
   
# creating a form 
class InputForm(forms.Form):
   
    
    first_name = forms.CharField()

class TranslateForm(forms.Form):
    placeholder = forms.CharField()

TextToSpeech/main/views.py
from django.shortcuts import render

from django.http import HttpResponse
import json
from django.shortcuts import *
from django.template import RequestContext
import json
from django.shortcuts import *
from django.template import RequestContext
from main.dataHandler import DataHanlder
from main.forms import InputForm, TranslateForm

def index(request):
    return render(request, "toSpeech.html")
def text_to_speech(request):
    return render(request, "toSpeech.html")
def text_utils(request):
    return render(request, "text_utils.html")
def translate_view(request):
    return render(request, "translate.html")

def temp(request):
    returnValue = ""
    if request.method == "POST":
        print(request.POST)
        data = request.POST["input_area"]
        convertion_type = request.POST["convertion_type"]

        handler = DataHanlder(data, convertion_type)
        returnValue = handler.handle()
        
    return HttpResponse(json.dumps({'message': returnValue}), content_type="application/json")

# def something(request):
#     context ={}
#     context['form']= InputForm()
#     return render(request, "something.html", context)

TextToSpeech/main/templates/hello.html
<html>
    <head>
    </head>
    <body>
        <p id ="p1">hello</p>
        <form id="some_form" action="world" method="post">{% csrf_token %}
            <input id="in1" type="submit" value="Submit Feedback" />
        </form>
        
        <script>
        document.getElementById("in1").style.display='none';
        document.getElementById("in1").click();
        
        </script>
    </body>
</html>

TextToSpeech/main/templates/something.html
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
<body>
    <!-- <script>
        console.log("Here1")
        $("#friend_form").submit(function(e){
            console.log("Here2")
    $.post('/url/', $(this).serialize(), function(data){
        console.log("Here3")
        $('.message').html(JSON.parse(data).message);
       // of course you can do something more fancy with your respone
    });
    e.preventDefault();
});
</script> -->
<script type="text/javascript">
    $(document).ready(function() {
        // console.log($('#messages').html)
        $('#friend_form').submit(function() { // On form submit event
            $.ajax({ // create an AJAX call...
                data: $(this).serialize(), // get the form data
                type: $(this).attr('method'), // GET or POST
                url: "/main/temp", // the file to call
                success: function(response) { // on success..
                    console.log($('#friend_form').attr('action'))
                    console.log(response)
                    console.log(response.message)
                    
                    console.log("success")
                    console.log($('message').html)
                    $('#message').html(response.message); // update the DIV
                },
                error: function(e, x, r) { // on error..
                    console.log("error")
                    $('#message').html(e); // update the DIV
                }
            });
            return false;
        });
    });
    i = 0;


$(document).ready(function(){

//setup before functions
var typingTimer;                //timer identifier
var doneTypingInterval = 500;  //time in ms (5 seconds)
//on keyup, start the countdown
$('#id_first_name').keyup(function(){
    clearTimeout(typingTimer);
    if ($('#id_first_name').val()) {
        document.getElementById("message").innerHTML = "...";
        typingTimer = setTimeout(doneTyping, doneTypingInterval);
    }
});

//user is "finished typing," do something
function doneTyping () {
    //do something
    $('#friend_form').submit();
}

//   $("#id_first_name").keyup(function(){
//     $("span").text(i += 1);
//     $('#friend_form').submit();
//   });
});
    </script>
    <h1>Leave a Suggestion Here</h1>
        <div id="message" class="message">bla</div>
        <div>
            <form id="friend_form" action="" method="post">{% csrf_token %}
                {{ form.as_table }}
                <input type="submit" />
            </form>
        </div>
        Enter your name: <input type="text" id = "input">

<p>Keypresses: <span>0</span></p>
<div>
    <form id="some_form" action="/main/temp" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit Feedback" />
    </form>
</div>
</body>
</html>

TextToSpeech/main/templates/temp.html
<p>Hello World</p>

TextToSpeech/main/templates/text_utils.html
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <meta charset="UTF-8">
        <style>
            table tr td {
    border: 1px solid #ccc;
    margin: 0 auto;
    
}
.disappear {
    display: none;
}
.collapsed {
    visibility: collapse;
}

textarea {
  resize: none;
  font-size: 30px;
  font-family: monospace;
}

label.label-checkbox {
  cursor: pointer;
}


label.label-checkbox input {
  position: absolute;
  top: 0;
  left: 0;
  visibility: hidden;
  pointer-events: none;
}

label.label-checkbox span {
  padding: 11px 21px;
  border: 1px solid #ccc;
  display: inline-block;
  color: #202020;
  border-radius: 6px;
  margin: 7px;
  background: #f5f5f5;
  user-select: none;
}

label.label-checkbox input:checked + span {
  box-shadow: inset 1px 2px 5px #777;
  transform: translateY(1px);
  background: #e5e5e5;
}
button {
  background: #ededed;
  border: 1px solid #ccc;
  padding: 10px 30px;
  border-radius: 3px;
  cursor: pointer;
}

button:active {
  background: #e5e5e5;
  -webkit-box-shadow: inset 0px 0px 5px #c1c1c1;
     -moz-box-shadow: inset 0px 0px 5px #c1c1c1;
          box-shadow: inset 0px 0px 5px #c1c1c1;
   outline: none;
}
textarea {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;

    width: 100%;
}
.center {
  margin-left: auto;
  margin-right: auto;
}
h1 { color: #fe921f; font-family: 'Lato', sans-serif; font-size: 54px; font-weight: 300; line-height: 58px; margin: 0 0 58px; text-align: center; }


p { color: #adb7bd; font-family: 'Lucida Sans', Arial, sans-serif; font-size: 16px; line-height: 26px; text-indent: 30px; margin: 0; }


a { color: #ffffff; text-decoration: underline; }
h2 { color: #ffffff; text-align: center;}
h3 { color: #ffffff; text-align: center;}

a:hover { color: #ffffff }

body {
  background-color: rgb(46, 46, 46);
}
.date { background: #fe921f; color: #ffffff; display: inline-block; font-family: 'Lato', sans-serif; font-size: 12px; font-weight: bold; line-height: 12px; letter-spacing: 1px; margin: 0 0 30px; padding: 10px 15px 8px; text-transform: uppercase; }
        </style>
    </head>
<body>

    <br><br>
    <h1>Text Utils!</h1>
    <div>
        <h2>Make your text even better!</h2>
    </div>
        <div>
            
            <form  id="friend_form" action="" method="post">{% csrf_token %}
            </form>
        </div>
            <table class="center" style="width:80%; max-width:80%;" cellborder="1">
                <tr>
                    <center>
                    <button id="switch_btn" style="font-size:larger; font-weight: bold;" onclick="switchText()">&#8644;</button>
                    </center>
                </tr>
                <tr>
                    <td>
                        <textarea readonly style="background: #f0efef;" dir="ltr" id="output_area" cols="45" rows="10"></textarea>
                    </td>                    
                    <td>
                        <textarea dir="rtl" name="" id="input_area" cols="45" rows="10"></textarea>
                    </td>
                </tr>
                <tr>
                    <!-- <td class="collapsed" align="right"></td> -->
                    <!-- <td style="border: 0px; vertical-align: top; text-align: center;"> -->
                    <td style="border: 0px; text-align: center;">
                        <button id="copy_btn">Copy</button>
                    </td>

                    <td align="right" style="border: 0px;">
                        <label class="label-checkbox">
                        <input type="radio" id="Decryption" name="convertion_group" onclick="sendHelperForm()">
                        <span>Decryption</span>
                        </label>
                        <label class="label-checkbox">
                        <input type="radio" id="Encryption" name="convertion_group" onclick="sendHelperForm()">
                        <span>Encryption</span>
                        </label>
                        <label class="label-checkbox">
                        <input type="radio" id="Reverse" name="convertion_group" onclick="sendHelperForm()">
                        <span>Reverse</span>
                        <label class="label-checkbox">
                        <input type="radio" id="ToLower" name="convertion_group" onclick="sendHelperForm()">
                        <span>ToLower</span>
                        </label>
                        <label class="label-checkbox">
                        <input type="radio" id="ToUpper" name="convertion_group" onclick="sendHelperForm()">
                        <span>ToUpper</span>
                        </label>
                        <label class="label-checkbox">
                        <input type="radio" id="Numerology" name="convertion_group" onclick="sendHelperForm()" checked>
                        <span title="Support Hebrew only">Numerology</span>
                        </label>
                    </td>
                </tr>
            </table>
            <br>
            <br>
            <a href="text_to_speech"><h2>Visit Hebrew Text to Speech!</h2></a>
            <a href="translate"><h2>Visit Translator!</h2></a>
</div>


<script type="text/javascript">
    $(document).ready(function() {

        //Function to send POST with any desired data
        $('#friend_form').submit(function() { // On form submit event
            var convertion_type = document.querySelector('input[name="convertion_group"]:checked').id;
            //The form contains the csrf token
            var data = $(this).serializeArray(); // convert form to array
            data.push({name: "input_area", value:  document.getElementById('input_area').value});
            data.push({name: "convertion_type", value:  convertion_type});

            $.ajax({ // create an AJAX call...
                data: $.param(data), // get the form data
                type: $(this).attr('method'), // GET or POST
                url: "/main/temp", // the file to call
                success: function(response) { // on success..
                    $('#output_area').val(response.message); // update the DIV
                },
                error: function(e, x, r) { // on error..
                    console.log("error")
                    $('#output_area').html(e); // update the DIV
                }
            });
            return false;
        });
    });

$(document).ready(function(){

//setup before functions
var typingTimer;                //timer identifier
var doneTypingInterval = 200;  //time in ms (5 seconds)
//on keyup, start the countdown
$('#input_area').keyup(function(){
    console.log("in keyup")
    clearTimeout(typingTimer);
    if ($('#input_area').val()) {
        document.getElementById("output_area").value = "...";
        typingTimer = setTimeout(doneTyping, doneTypingInterval);
    }
});

//user is "finished typing," do something
function doneTyping () {
    //do something
    $('#friend_form').submit();
}

});
function sendHelperForm() {
    document.getElementById("output_area").innerHTML = "...";
    $('#friend_form').submit();
}

$("#copy_btn").click(function(e) {
    e.preventDefault();
    document.execCommand('copy', false, document.getElementById('output_area').select());
});

function switchText(){
    let temp = document.getElementById("input_area").value;
    document.getElementById("input_area").value = document.getElementById("output_area").value;
    document.getElementById("output_area").value = temp;
}
</script>

</body>
</html>

TextToSpeech/main/templates/toSpeech.html
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <meta charset="UTF-8">
        <style>
            table tr td {
    border: 1px solid #ccc;
    margin: 0 auto;
    
}
.disappear {
    display: none;
}
.collapsed {
    visibility: collapse;
}

textarea {
  resize: none;
  font-size: 30px;
  font-family: monospace;
}

label.label-checkbox {
  cursor: pointer;
}


label.label-checkbox input {
  position: absolute;
  top: 0;
  left: 0;
  visibility: hidden;
  pointer-events: none;
}

label.label-checkbox span {
  padding: 11px 21px;
  border: 1px solid #ccc;
  display: inline-block;
  color: #202020;
  border-radius: 6px;
  margin: 7px;
  background: #f5f5f5;
  user-select: none;
}

label.label-checkbox input:checked + span {
  box-shadow: inset 1px 2px 5px #777;
  transform: translateY(1px);
  background: #e5e5e5;
}
button {
  background: #ededed;
  border: 1px solid #ccc;
  padding: 10px 30px;
  border-radius: 3px;
  cursor: pointer;
}

button:active {
  background: #e5e5e5;
  -webkit-box-shadow: inset 0px 0px 5px #c1c1c1;
     -moz-box-shadow: inset 0px 0px 5px #c1c1c1;
          box-shadow: inset 0px 0px 5px #c1c1c1;
   outline: none;
}
textarea {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;

    width: 100%;
}
.center {
  margin-left: auto;
  margin-right: auto;
}
h1 { color: #fe921f; font-family: 'Lato', sans-serif; font-size: 54px; font-weight: 300; line-height: 58px; margin: 0 0 58px; text-align: center; }


p { color: #adb7bd; font-family: 'Lucida Sans', Arial, sans-serif; font-size: 16px; line-height: 26px; text-indent: 30px; margin: 0; }


a { color: #ffffff; text-decoration: underline; }
h2 { color: #ffffff; text-align: center;}
h3 { color: #ffffff; text-align: center;}

a:hover { color: #ffffff }

body {
  background-color: rgb(46, 46, 46);
}
.date { background: #fe921f; color: #ffffff; display: inline-block; font-family: 'Lato', sans-serif; font-size: 12px; font-weight: bold; line-height: 12px; letter-spacing: 1px; margin: 0 0 30px; padding: 10px 15px 8px; text-transform: uppercase; }
        </style>
    </head>
<body>

    <br><br>
    <h1>Hebrew Text to Speech!</h1>
    <div>
        <h2>Take your text with you as a podcast!</h2>
    </div>
        <div>
            <form  id="friend_form" action="" method="post">{% csrf_token %}
            </form>
        </div>
            <table class="center" style="width:50%; max-width:80%;" cellborder="1">
                <tr>                    
                    <td>
                        <textarea dir="rtl" name="" id="input_area" cols="45" rows="10"></textarea>
                    </td>
                </tr>
                <tr>
                    <td style="border: 0px; text-align: center;">
                        <button id="play_btn" onclick="playbtn_click()">Play</button>
                    </td>
                </tr>
            </table>
            <div style="text-align: center;">
                <a>
                    <audio style="visibility: hidden;" id="audio" controls="controls" controls="download">
                        <source id="audioSource" src="https://voice.reverso.net/RestPronunciation.svc/v1/output=json/GetVoiceStream/voiceName=he-IL-Asaf?inputText=16nXnNeV150g15DXoNeZINeQ15nXpteZ16c=" type="audio/mpeg">
                      Your browser does not support the audio element.
                      </audio>
                </a>
            </div>
            <br>
            <br>
            <a href="text_utils"><h2>Visit Text Utils!</h2></a>
            <a href="translate"><h2>Visit Translator!</h2></a>
        
</div>


<script type="text/javascript">
    $(document).ready(function() {

        //Function to send POST with any desired data
        $('#friend_form').submit(function() { // On form submit event
            var convertion_type = "TextToSpeechPlay"
            //The form contains the csrf token
            var data = $(this).serializeArray(); // convert form to array
            data.push({name: "input_area", value:  document.getElementById('input_area').value});
            data.push({name: "convertion_type", value:  convertion_type});

            // //Set the value of the form's field in order to submit it
            // document.getElementById('id_placeholder').value = document.getElementById('input_area').value

            $.ajax({ // create an AJAX call...
                data: $.param(data), // get the form data
                type: $(this).attr('method'), // GET or POST
                url: "/main/temp", // the file to call
                success: function(response) { // on success..
                    console.log(document.getElementById('audioSource').value)
                    // $('#audioSource').val(response.message); // update the DIV
                    var source = document.getElementById('audioSource');
                    source.src = response.message;
                    console.log(document.getElementById('audioSource').src)
                    if (convertion_type == "TextToSpeechPlay") {
                        var audio = document.getElementById('audio');

                        console.log("playbtn_click")
                        audio.load(); //call this to just preload the audio without playing
                        audio.play(); //call this to play the song right away
                    }
                },
                error: function(e, x, r) { // on error..
                    console.log("error")
                    // $('#output_area').html(e); // update the DIV
                }
            });
            return false;
        });
    });

// $(document).ready(function(){

// //setup before functions
// var typingTimer;                //timer identifier
// var doneTypingInterval = 200;  //time in ms (5 seconds)
// //on keyup, start the countdown
// $('#input_area').keyup(function(){
//     console.log("in keyup")
//     clearTimeout(typingTimer);
//     if ($('#input_area').val()) {
//         document.getElementById("output_area").value = "...";
//         typingTimer = setTimeout(doneTyping, doneTypingInterval);
//     }
// });

// //user is "finished typing," do something
// function doneTyping () {
//     //do something
//     $('#friend_form').submit();
// }

// });
// function sendHelperForm() {
//     document.getElementById("output_area").innerHTML = "...";
//     $('#friend_form').submit();
// }

// $("#copy_btn").click(function(e) {
//     e.preventDefault();
//     console.log( document.getElementById('output_area').value)
//     document.execCommand('copy', false, document.getElementById('output_area').select());
// });

// function switchText(){
//     console.log("here")
//     console.log(document.getElementById("input_area").value)
//     console.log(document.getElementById("input_area").innerHTML)

//     let temp = document.getElementById("input_area").value;
//     document.getElementById("input_area").value = document.getElementById("output_area").value;
//     document.getElementById("output_area").value = temp;
// }

function playbtn_click(){
    // e.preventDefault();
    if ($('#input_area').val()) {
        document.getElementById("audio").style.visibility = "visible";
        
        $('#friend_form').submit();
    }
}

</script>

</body>
</html>

TextToSpeech/main/templates/translate.html
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <style>
            table tr td {
    border: 1px solid #ccc;
    margin: 0 auto;
    
}
.disappear {
    display: none;
}
.collapsed {
    visibility: collapse;
}

textarea {
  resize: none;
  font-size: 30px;
  font-family: monospace;
}

label.label-checkbox {
  cursor: pointer;
}


label.label-checkbox input {
  position: absolute;
  top: 0;
  left: 0;
  visibility: hidden;
  pointer-events: none;
}

label.label-checkbox span {
  padding: 11px 21px;
  border: 1px solid #ccc;
  display: inline-block;
  color: #202020;
  border-radius: 6px;
  margin: 7px;
  background: #f5f5f5;
  user-select: none;
}

label.label-checkbox input:checked + span {
  box-shadow: inset 1px 2px 5px #777;
  transform: translateY(1px);
  background: #e5e5e5;
}
button {
  background: #ededed;
  border: 1px solid #ccc;
  padding: 10px 30px;
  border-radius: 3px;
  cursor: pointer;
}

button:active {
  background: #e5e5e5;
  -webkit-box-shadow: inset 0px 0px 5px #c1c1c1;
     -moz-box-shadow: inset 0px 0px 5px #c1c1c1;
          box-shadow: inset 0px 0px 5px #c1c1c1;
   outline: none;
}
textarea {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;

    width: 100%;
}
.center {
  margin-left: auto;
  margin-right: auto;
}
h1 { color: #fe921f; font-family: 'Lato', sans-serif; font-size: 54px; font-weight: 300; line-height: 58px; margin: 0 0 58px; text-align: center; }


p { color: #adb7bd; font-family: 'Lucida Sans', Arial, sans-serif; font-size: 16px; line-height: 26px; text-indent: 30px; margin: 0; }


a { color: #ffffff; text-decoration: underline; }
h2 { color: #ffffff; text-align: center;}
h3 { color: #ffffff; text-align: center;}

a:hover { color: #ffffff }

body {
  background-color: rgb(46, 46, 46);
}
.date { background: #fe921f; color: #ffffff; display: inline-block; font-family: 'Lato', sans-serif; font-size: 12px; font-weight: bold; line-height: 12px; letter-spacing: 1px; margin: 0 0 30px; padding: 10px 15px 8px; text-transform: uppercase; }
        </style>
    </head>
<body>

    <br><br>
    <h1>Hebrew-English Translator</h1>
    <div>
        <h2>With the ability to hear your translated Hebrew words as well!</h2>
    </div>
        <div>
            
            <form  id="friend_form" action="" method="post">{% csrf_token %}
            </form>
        </div>
            <table class="center" style="width:80%; max-width:80%;" cellborder="1">
                <tr>
                    <center>
                    <button id="switch_btn" style="font-size:larger; font-weight: bold;" onclick="switchText()">&#8644;</button>
                    </center>
                </tr>
                <tr>
                    <td>
                        <textarea readonly style="background: #f0efef;" dir="rtl" id="output_area" cols="45" rows="10"></textarea>
                    </td>                    
                    <td>
                        <textarea dir="rtl" name="" id="input_area" cols="45" rows="10"></textarea>
                    </td>
                </tr>
                <tr>
                    <!-- <td class="collapsed" align="right"></td> -->
                    <!-- <td style="border: 0px; vertical-align: top; text-align: center;"> -->
                    <td style="border: 0px; text-align: center;">
                        <button id="copy_btn">Copy</button>
                        <button id="play_btn" onclick="playbtn_click()"><i class="fa fa-volume-up" style="font-size:larger;"></i></button>
                    </td>

                    <!-- <td align="right" style="border: 0px;">
                        <label class="label-checkbox">
                        <input type="radio" id="Decryption" name="convertion_group" onclick="sendHelperForm()">
                        <span>Decryption</span>
                        </label>
                        <label class="label-checkbox">
                        <input type="radio" id="Encryption" name="convertion_group" onclick="sendHelperForm()">
                        <span>Encryption</span>
                        </label>
                        <label class="label-checkbox">
                        <input type="radio" id="ToLower" name="convertion_group" onclick="sendHelperForm()">
                        <span>ToLower</span>
                        </label>
                        <label class="label-checkbox">
                        <input type="radio" id="ToUpper" name="convertion_group" onclick="sendHelperForm()">
                        <span>ToUpper</span>
                        </label>
                        <label class="label-checkbox">
                        <input type="radio" id="Translate" name="convertion_group" onclick="sendHelperForm()" checked>
                        <span>Translate</span>
                        </label>
                        <label class="label-checkbox">
                        <input type="radio" id="Numerology" name="convertion_group" onclick="sendHelperForm()" checked>
                        <span>Numerology</span>
                        </label>
                    </td> -->
                </tr>
            </table>
            <h2 style="font-size: medium;">Translations from Google.com, voices from Reverso.net</h2>
            <br>
            <br>
            <a href="text_to_speech"><h2>Visit Hebrew Text to Speech!</h2></a>
            <a href="text_utils"><h2>Visit Text Utils!</h2></a>
            <div style="text-align: center;">
                <a>
                    <audio style="visibility: hidden;" id="audio" controls="controls" controls="download">
                        <source id="audioSource" src="https://voice.reverso.net/RestPronunciation.svc/v1/output=json/GetVoiceStream/voiceName=he-IL-Asaf?inputText=16nXnNeV150g15DXoNeZINeQ15nXpteZ16c=" type="audio/mpeg">
                      Your browser does not support the audio element.
                      </audio>
                </a>
            </div>
</div>


<script type="text/javascript">
    global_convertion_type = "Translate";
    $(document).ready(function() {

        //Function to send POST with any desired data
        $('#friend_form').submit(function() { // On form submit event
            var convertion_type = global_convertion_type;
            //The form contains the csrf token
            var data = $(this).serializeArray(); // convert form to array
            value_to_translate = document.getElementById('input_area').value;

            if (convertion_type == "TextToSpeechPlay") {
                //If we want to listen,
                //it would be to the result (output area) and not to what the user types
                value_to_translate = document.getElementById('output_area').value;
            }
            data.push({name: "input_area", value: value_to_translate});
            data.push({name: "convertion_type", value:  convertion_type});

            $.ajax({ // create an AJAX call...
                data: $.param(data), // get the form data
                type: $(this).attr('method'), // GET or POST
                url: "/main/temp", // the file to call
                success: function(response) { // on success..
                    if (convertion_type == "Translate") {
                        text_direction = contains_heb(response.message)? 'rtl' : 'ltr';
                        $('#output_area').css('direction', text_direction);
                        $('#output_area').val(response.message); // update the DIV
                    }
                    else if (convertion_type == "TextToSpeechPlay") {
                        var source = document.getElementById('audioSource');
                        source.src = response.message;
                        var audio = document.getElementById('audio');
                        audio.load(); //call this to just preload the audio without playing
                        audio.play(); //call this to play the song right away
                    }

                },
                error: function(e, x, r) { // on error..
                    console.log("error")
                    $('#output_area').html(e); // update the DIV
                }
            });
            return false;
        });
    });

function contains_heb(str) {
    return (/[\u0590-\u05FF]/).test(str);
}

$(document).ready(function(){

//setup before functions
var typingTimer;                //timer identifier
var doneTypingInterval = 200;  //time in ms (5 seconds)
//on keyup, start the countdown
$('#input_area').keyup(function(){
    console.log("in keyup")
    clearTimeout(typingTimer);
    if ($('#input_area').val()) {
        document.getElementById("output_area").value = "...";
        typingTimer = setTimeout(doneTyping, doneTypingInterval);
    }
});

//user is "finished typing," do something
function doneTyping () {
    //do something
    $('#friend_form').submit();
}

});
function sendHelperForm() {
    document.getElementById("output_area").innerHTML = "...";
    $('#friend_form').submit();
}

$("#copy_btn").click(function(e) {
    e.preventDefault();
    document.execCommand('copy', false, document.getElementById('output_area').select());
});

function switchText(){
    let temp = document.getElementById("input_area").value;
    document.getElementById("input_area").value = document.getElementById("output_area").value;
    document.getElementById("output_area").value = temp;
    sendHelperForm();
}
function playbtn_click(){
    if ($('#input_area').val()) {
        global_convertion_type = "TextToSpeechPlay"
        $('#friend_form').submit();
        global_convertion_type = "Translate";
    }
}
</script>

</body>
</html>

TextToSpeech/main/templates/world.html
<p>World!</p>